### ISSUE TITLE
[Build Failed] on [Добавлен фронтенд модуль](196) for commit 59695ab177e2178c33beb2916a6c0a3f40e3cbe3

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#197]
Workflow failed for commit 59695ab177e2178c33beb2916a6c0a3f40e3cbe3. Fails: #196

**Comment by Spec163** [comment]
Ругается на отсутствие тестов, но так и должно, ибо это модуль фронта (нужно изменить настройки проверок)
