### ISSUE TITLE
[Build Failed] on [Restyle WIP Доработка фронтенда](323) for commit b2de9cb60941d368e40dccd0abd9bd71b2c3fe43

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#325]
Workflow failed for commit b2de9cb60941d368e40dccd0abd9bd71b2c3fe43. Fails: #323

**Comment by Spec163** [comment]
fiexed https://github.com/kostua16/UNC_2020_MS_TLT/pull/321/commits/b79e49c98b9d94b5b12f4ab1074dee64e95d32cd
