### ISSUE TITLE
[Build Failed] on [Restyle WIP Доработка фронтенда](323) for commit a6f295ef8fa0f19770552a9fb6047f325edf2aeb

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#329]
Workflow failed for commit a6f295ef8fa0f19770552a9fb6047f325edf2aeb. Fails: #323

**Comment by Spec163** [comment]
fiexed https://github.com/kostua16/UNC_2020_MS_TLT/pull/321/commits/b79e49c98b9d94b5b12f4ab1074dee64e95d32cd
