### ISSUE TITLE
[Build Failed] on [fix bugs](334) for commit ac91ad4613ce0b53d883419c1a2489ab4d2aa2dd

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#335]
Workflow failed for commit ac91ad4613ce0b53d883419c1a2489ab4d2aa2dd. Fails: #334

**Comment by Spec163** [comment]
fixed https://github.com/kostua16/UNC_2020_MS_TLT/pull/344/commits/efba35b91be1ab188522f1eeef7a17a3537fa93a
