### ISSUE TITLE
[Build Failed] on [Restyle WIP Fix docs](346) for commit 1948bf6e4936ab550ed57b9406f4432c4d7b879c

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#348]
Workflow failed for commit 1948bf6e4936ab550ed57b9406f4432c4d7b879c. Fails: #346

**Comment by Spec163** [comment]
fixed https://github.com/kostua16/UNC_2020_MS_TLT/pull/344/commits/efba35b91be1ab188522f1eeef7a17a3537fa93a
