### ISSUE TITLE
[Build Failed] on [Restyle Fix docs](357) for commit 83e007ca278418b535379f7f65d9ea969456d7e1

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#359]
Workflow failed for commit 83e007ca278418b535379f7f65d9ea969456d7e1. Fails: #357

**Comment by Spec163** [comment]
fixed https://github.com/kostua16/UNC_2020_MS_TLT/pull/344/commits/0ebf9dcc0146087619fda4c5a1487f2879293a6e
