### ISSUE TITLE
[Build Failed] on [Restyle Fix docs](357) for commit 03c794deb77a521c7284adb45c95e79d081c3ed7

### ISSUE THREAD

**Issue by kostua16** [kostua16/UNC_2020_MS_TLT#361]
Workflow failed for commit 03c794deb77a521c7284adb45c95e79d081c3ed7. Fails: #357

**Comment by Spec163** [comment]
fixed https://github.com/kostua16/UNC_2020_MS_TLT/pull/344/commits/0ebf9dcc0146087619fda4c5a1487f2879293a6e
